'use client'
import { createContext, useContext, useState, useEffect, ReactNode } from 'react'
export type Lang = 'en'|'yo'|'ha'|'ar'|'fr'
export const LANGUAGES = [
  {code:'en' as Lang,name:'English', flag:'🇬🇧',dir:'ltr'},
  {code:'yo' as Lang,name:'Yoruba',  flag:'🇳🇬',dir:'ltr'},
  {code:'ha' as Lang,name:'Hausa',   flag:'🇳🇬',dir:'ltr'},
  {code:'ar' as Lang,name:'العربية', flag:'🇦🇪',dir:'rtl'},
  {code:'fr' as Lang,name:'Français',flag:'🇫🇷',dir:'ltr'},
]
export type T = { hero_badge:string;hero_cta:string;hero_sub:string;hero_built:string;hero_demo:string;nav_signin:string;nav_signup:string;nav_simulate:string;prob_label:string;prob_title:string;prob_sub:string;steps_label:string;steps_title:string;feat_label:string;feat_title:string;cta_title:string;cta_sub:string;cta_btn:string;footer_sub:string }
export const T: Record<Lang,T> = {
  en:{ hero_badge:'Cross-Border Payment Intelligence',hero_cta:'Get Started Free',hero_sub:'Stop overpaying on cross-border transfers. RouteWise analyzes every payment rail across 15 currencies to find your optimal route.',hero_built:'Built as a decision intelligence layer on top of payment infrastructure like Interswitch.',hero_demo:'Try Demo',nav_signin:'Sign In',nav_signup:'Sign Up Free',nav_simulate:'Simulate',prob_label:'The Problem',prob_title:'SMEs lose billions to hidden payment fees',prob_sub:'Every cross-border payment involves FX spreads and variable fees. Without intelligent routing, businesses overpay by 3–8%.',steps_label:'How It Works',steps_title:'From input to optimal route in seconds',feat_label:'Features',feat_title:'Built for payment intelligence',cta_title:'Ready to optimize your payments?',cta_sub:'Start free. No credit card required. 15 currencies, 4 payment rails.',cta_btn:'Create Free Account',footer_sub:'Cross-border payment intelligence for SMEs.' },
  yo:{ hero_badge:'Ìmọ̀ Ìsanpá Àgbáyé',hero_cta:'Bẹ̀rẹ̀ Ọ̀fẹ́',hero_sub:'Dáwọ́ san owó àfikún. RouteWise ṣe àgbéyẹ̀wò gbogbo ọ̀nà ìsanpá kọjá 15 owó.',hero_built:'A kọ rẹ̀ gẹ́gẹ́ bí ìpele ìmọ̀ ìpinnu lórí àwọn ètò ìsanpá bíi Interswitch.',hero_demo:'Gbìyànjú Demo',nav_signin:'Wọlé',nav_signup:'Forúkọ Sílẹ̀',nav_simulate:'Ṣe Ìdánwò',prob_label:'Ìṣòro',prob_title:'Àwọn SME ń pàdánù owó nítorí owó ìdíyelé tó farapamọ́',prob_sub:'Gbogbo ìsanpá àgbáyé ní FX spreads àti àkókò ìtúsílẹ̀ tó yàtọ̀. Láìsí ọ̀nà ọgbọ́n àwọn iṣowo san 3-8% ju.',steps_label:'Bí Ó Ṣe Ń Ṣiṣẹ́',steps_title:'Láti ìgbéwọlé sí ọ̀nà tó dára jùlọ ní ìṣẹ́jú',feat_label:'Àwọn Ẹ̀yà',feat_title:'A kọ fún ìmọ̀ ìsanpá',cta_title:'Ṣé o ṣetán láti ṣe àmúnibọ̀wọ̀ ìsanpá rẹ?',cta_sub:'Bẹ̀rẹ̀ ọ̀fẹ́. Kò nílò káàdì kirẹditi. 15 owó, 4 ọ̀nà.',cta_btn:'Ṣẹ̀dá Àkáǹtì Ọ̀fẹ́',footer_sub:'Ìmọ̀ ìsanpá àgbáyé fún àwọn SME.' },
  ha:{ hero_badge:'Hankali na Biyan Kudi na Ƙasashen Waje',hero_cta:'Fara Kyauta',hero_sub:'Daina biyan kuɗi fiye da kima. RouteWise yana nazarin duk hanyoyin biyan kuɗi a cikin kuɗaɗe 15.',hero_built:'An gina shi a matsayin mataki na hankali a saman kayan aikin biyan kuɗi kamar Interswitch.',hero_demo:'Gwada Demo',nav_signin:'Shiga',nav_signup:'Yi Rajista',nav_simulate:'Gwadawa',prob_label:'Matsalar',prob_title:'Yan kasuwa na rasa biliyoyin saboda kudin ɓoye',prob_sub:'Kowane biyan kuɗi yana da farashin FX da lokacin sasantawa daban-daban. Ba tare da jagorar hankali ba kasuwanci na biyan 3-8% fiye.',steps_label:'Yadda Yake Aiki',steps_title:'Daga shigarwa zuwa mafi kyawun hanya cikin dakika',feat_label:'Abubuwan',feat_title:'An gina don hankali na biyan kuɗi',cta_title:'Kana shirye don inganta biyan kuɗinka?',cta_sub:'Fara kyauta. Ba a buƙatar katin kuɗi. Kuɗaɗe 15, hanyoyi 4.',cta_btn:'Ƙirƙiri Asusun Kyauta',footer_sub:'Hankali na biyan kuɗi na ƙasashen waje don yan kasuwa.' },
  ar:{ hero_badge:'ذكاء المدفوعات العابرة للحدود',hero_cta:'ابدأ مجاناً',hero_sub:'توقف عن الدفع الزائد. يحلل RouteWise كل مسار دفع عبر 15 عملة.',hero_built:'مبني كطبقة ذكاء قرار فوق البنية التحتية للمدفوعات مثل Interswitch.',hero_demo:'جرب العرض',nav_signin:'تسجيل الدخول',nav_signup:'إنشاء حساب',nav_simulate:'محاكاة',prob_label:'المشكلة',prob_title:'تخسر الشركات المليارات بسبب الرسوم المخفية',prob_sub:'كل دفعة عابرة للحدود تتضمن فروق أسعار الصرف ورسوم متغيرة. بدون توجيه ذكي تدفع 3-8٪ زيادة.',steps_label:'كيف يعمل',steps_title:'من الإدخال إلى المسار الأمثل في ثوانٍ',feat_label:'الميزات',feat_title:'مبني لذكاء المدفوعات',cta_title:'هل أنت مستعد لتحسين مدفوعاتك؟',cta_sub:'ابدأ مجاناً. لا يلزم بطاقة. 15 عملة و4 مسارات.',cta_btn:'إنشاء حساب مجاني',footer_sub:'ذكاء المدفوعات العابرة للحدود للشركات.' },
  fr:{ hero_badge:'Intelligence de paiements transfrontaliers',hero_cta:'Commencer gratuitement',hero_sub:"Arrêtez de surpayer. RouteWise analyse chaque voie de paiement sur 15 devises.",hero_built:"Conçu comme une couche d'intelligence au-dessus de l'infrastructure de paiement.",hero_demo:'Essayer la démo',nav_signin:'Se connecter',nav_signup:"S'inscrire",nav_simulate:'Simuler',prob_label:'Le problème',prob_title:'Les PME perdent des milliards à cause de frais cachés',prob_sub:'Chaque paiement transfrontalier implique des spreads de change et des frais variables. Sans routage intelligent les entreprises surpaient de 3-8%.',steps_label:'Comment ça marche',steps_title:"De la saisie à l'itinéraire optimal en secondes",feat_label:'Fonctionnalités',feat_title:"Conçu pour l'intelligence de paiement",cta_title:'Prêt à optimiser vos paiements ?',cta_sub:'Commencez gratuitement. Sans carte. 15 devises, 4 voies.',cta_btn:'Créer un compte gratuit',footer_sub:'Intelligence de paiement transfrontalier pour PME.' },
}
type LangCtx = { lang:Lang;setLang:(l:Lang)=>void;t:T;dir:string }
const LC = createContext<LangCtx>({ lang:'en',setLang:()=>{},t:T['en'],dir:'ltr' })
export function LangProvider({ children }: { children:ReactNode }) {
  const [lang,setLangState] = useState<Lang>('en')
  useEffect(() => {
    const saved = localStorage.getItem('rw-lang') as Lang
    if (saved && T[saved]) { setLangState(saved); document.documentElement.setAttribute('dir',LANGUAGES.find(l=>l.code===saved)?.dir||'ltr') }
  }, [])
  const setLang = (l:Lang) => { setLangState(l); localStorage.setItem('rw-lang',l); const dir=LANGUAGES.find(x=>x.code===l)?.dir||'ltr'; document.documentElement.setAttribute('dir',dir); document.documentElement.setAttribute('lang',l) }
  return <LC.Provider value={{ lang,setLang,t:T[lang],dir:LANGUAGES.find(x=>x.code===lang)?.dir||'ltr' }}>{children}</LC.Provider>
}
export const useLang = () => useContext(LC)
